In [1]:
import numpy as np
import pandas as pd

### Preparing The Training Dataset

#### Code Before Review

In [2]:
with open('Dataset/train/src-train.txt', 'r', encoding = 'utf-8-sig') as file:
    lines = file.readlines()

In [3]:
oc = list()
for line in lines:
    oc.append(line.strip())
    
oriCode = pd.DataFrame(data=oc, columns=['OriginalCode'])

In [4]:
oriCode

                                            OriginalCode
0      protected static String METHOD_1 ( String VAR_...
1      public TYPE_1 ( final String VAR_2 , final Str...
2      public void METHOD_1 ( Throwable VAR_1 ) { if ...
3      public TYPE_2 ( final String VAR_2 , final Str...
4      public void METHOD_1 ( ) { new TYPE_1 ( METHOD...
...                                                  ...
13751  protected void METHOD_1 ( TYPE_1 VAR_1 ) { sup...
13752  protected TYPE_1 METHOD_1 ( int position ) { f...
13753  int read ( ) { if ( this . hasNext ( ) == fals...
13754  public void METHOD_1 ( ) { TYPE_1 VAR_1 = TYPE...
13755  public TYPE_2 ( String VAR_2 , boolean VAR_3 )...

[13756 rows x 1 columns]

In [5]:
len(oriCode)

13756

#### Code Implemented Based on The Review Comment

In [6]:
with open('Dataset/train/tgt-train.txt', 'r', encoding = 'utf-8-sig') as file:
    lines = file.readlines()

In [7]:
rc = list()
for line in lines:
    rc.append(line.strip())
    
revCode = pd.DataFrame(data=rc, columns=['ReviewedCode'])

In [8]:
revCode

                                            ReviewedCode
0      protected static String METHOD_1 ( String VAR_...
1      public TYPE_1 ( final String VAR_2 , final Str...
2      public void METHOD_1 ( Throwable VAR_1 ) { Uti...
3      public TYPE_2 ( final String VAR_2 , final Str...
4      public void METHOD_1 ( ) { new TYPE_1 ( METHOD...
...                                                  ...
13751  protected void METHOD_1 ( TYPE_1 VAR_1 ) { sup...
13752  protected TYPE_1 METHOD_1 ( int position ) { f...
13753  int read ( ) { if ( ! this . hasNext ( ) ) { t...
13754  public void METHOD_1 ( ) { TYPE_1 VAR_1 = TYPE...
13755  public TYPE_2 ( String VAR_2 , boolean VAR_3 )...

[13756 rows x 1 columns]

### Merging OriginalCode and ReviewedCode into a single pandas DataFrame

In [9]:
data_train = pd.DataFrame(pd.concat([oriCode, revCode], axis=1))

In [10]:
data_train.head()

,OriginalCode,ReviewedCode
0,protected static String METHOD_1 ( String VAR_...,protected static String METHOD_1 ( String VAR_...
1,"public TYPE_1 ( final String VAR_2 , final Str...","public TYPE_1 ( final String VAR_2 , final Str..."
2,public void METHOD_1 ( Throwable VAR_1 ) { if ...,public void METHOD_1 ( Throwable VAR_1 ) { Uti...
3,"public TYPE_2 ( final String VAR_2 , final Str...","public TYPE_2 ( final String VAR_2 , final Str..."
4,public void METHOD_1 ( ) { new TYPE_1 ( METHOD...,public void METHOD_1 ( ) { new TYPE_1 ( METHOD...

### Preparing the validation data set

In [11]:
with open('Dataset/eval/src-val.txt', 'r', encoding = 'utf-8-sig') as file:
    lines = file.readlines()
    
oc_v = list()
for line in lines:
    oc_v.append(line.strip())
    
oriCode_v = pd.DataFrame(data=oc_v, columns=['OriginalCode'])

In [12]:
oriCode_v

                                           OriginalCode
0     public void METHOD_1 ( ) { String VAR_1 = TYPE...
1     public TYPE_1 METHOD_1 ( ) { if ( VAR_1 != nul...
2     private TYPE_1 METHOD_1 ( TYPE_2 VAR_1 , TYPE_...
3     public TYPE_5 ( TYPE_1 VAR_2 , boolean VAR_3 ,...
4     public static void METHOD_1 ( TYPE_1 VAR_1 , T...
...                                                 ...
1714  protected Map < TYPE_1 , TYPE_2 > METHOD_1 ( M...
1715  protected void METHOD_1 ( ) throws IOException...
1716  public static TYPE_1 getInstance ( ) { if ( VA...
1717  public static TYPE_1 parse ( String VAR_1 , bo...
1718  protected TYPE_1 METHOD_1 ( TYPE_1 . TYPE_5 da...

[1719 rows x 1 columns]

In [13]:
with open('Dataset/eval/tgt-val.txt', 'r', encoding = 'utf-8-sig') as file:
    lines = file.readlines()
    
rc_v = list()
for line in lines:
    rc_v.append(line.strip())
    
revCode_v = pd.DataFrame(data=rc_v, columns=['ReviewedCode'])

In [14]:
revCode_v

                                           ReviewedCode
0     public void METHOD_1 ( ) { VAR_2 = TYPE_2 . ME...
1     public TYPE_1 METHOD_1 ( ) { return VAR_2 . ME...
2     private TYPE_1 METHOD_1 ( TYPE_2 VAR_1 , TYPE_...
3     public TYPE_5 ( TYPE_1 VAR_2 , boolean VAR_3 ,...
4     public static void METHOD_1 ( TYPE_1 VAR_1 , T...
...                                                 ...
1714  protected Map < TYPE_1 , TYPE_2 > METHOD_1 ( M...
1715  protected boolean METHOD_1 ( ) { if ( VAR_1 <=...
1716  public static TYPE_1 getInstance ( ) { return ...
1717  public static TYPE_1 parse ( String VAR_1 , bo...
1718  protected TYPE_1 METHOD_1 ( TYPE_1 . TYPE_5 da...

[1719 rows x 1 columns]

In [15]:
data_val = pd.DataFrame(pd.concat([oriCode_v, revCode_v], axis=1))

In [16]:
data_val

,OriginalCode,ReviewedCode
0,public void METHOD_1 ( ) { String VAR_1 = TYPE...,public void METHOD_1 ( ) { VAR_2 = TYPE_2 . ME...
1,public TYPE_1 METHOD_1 ( ) { if ( VAR_1 != nul...,public TYPE_1 METHOD_1 ( ) { return VAR_2 . ME...
2,"private TYPE_1 METHOD_1 ( TYPE_2 VAR_1 , TYPE_...","private TYPE_1 METHOD_1 ( TYPE_2 VAR_1 , TYPE_..."
3,"public TYPE_5 ( TYPE_1 VAR_2 , boolean VAR_3 ,...","public TYPE_5 ( TYPE_1 VAR_2 , boolean VAR_3 ,..."
4,"public static void METHOD_1 ( TYPE_1 VAR_1 , T...","public static void METHOD_1 ( TYPE_1 VAR_1 , T..."
...,...,...
1714,"protected Map < TYPE_1 , TYPE_2 > METHOD_1 ( M...","protected Map < TYPE_1 , TYPE_2 > METHOD_1 ( M..."
1715,protected void METHOD_1 ( ) throws IOException...,protected boolean METHOD_1 ( ) { if ( VAR_1 <=...
1716,public static TYPE_1 getInstance ( ) { if ( VA...,public static TYPE_1 getInstance ( ) { return ...
1717,"public static TYPE_1 parse ( String VAR_1 , bo...","public static TYPE_1 parse ( String VAR_1 , bo..."
1718,protected TYPE_1 METHOD_1 ( TYPE_1 . TYPE_5 da...,protected TYPE_1 METHOD_1 ( TYPE_1 . TYPE_5 da...

### Merging The Training and Validating sets into one dataframe

In [17]:
final_train = pd.DataFrame(pd.concat([data_train, data_val]))

In [18]:
final_train

,OriginalCode,ReviewedCode
0,protected static String METHOD_1 ( String VAR_...,protected static String METHOD_1 ( String VAR_...
1,"public TYPE_1 ( final String VAR_2 , final Str...","public TYPE_1 ( final String VAR_2 , final Str..."
2,public void METHOD_1 ( Throwable VAR_1 ) { if ...,public void METHOD_1 ( Throwable VAR_1 ) { Uti...
3,"public TYPE_2 ( final String VAR_2 , final Str...","public TYPE_2 ( final String VAR_2 , final Str..."
4,public void METHOD_1 ( ) { new TYPE_1 ( METHOD...,public void METHOD_1 ( ) { new TYPE_1 ( METHOD...
...,...,...
1714,"protected Map < TYPE_1 , TYPE_2 > METHOD_1 ( M...","protected Map < TYPE_1 , TYPE_2 > METHOD_1 ( M..."
1715,protected void METHOD_1 ( ) throws IOException...,protected boolean METHOD_1 ( ) { if ( VAR_1 <=...
1716,public static TYPE_1 getInstance ( ) { if ( VA...,public static TYPE_1 getInstance ( ) { return ...
1717,"public static TYPE_1 parse ( String VAR_1 , bo...","public static TYPE_1 parse ( String VAR_1 , bo..."
1718,protected TYPE_1 METHOD_1 ( TYPE_1 . TYPE_5 da...,protected TYPE_1 METHOD_1 ( TYPE_1 . TYPE_5 da...

In [19]:
# final_train.to_csv("final_train", sep=',', index=False, encoding='utf-8')

In [21]:
import json

In [22]:
ftrain = final_train.to_dict(orient="records")

with open("train.jsonl", "w") as f:
    for line in ftrain:
        f.write(json.dumps(line) + "\n")

### Preparing the Testing dataset

In [2]:
with open('Dataset/test/src-test.txt', 'r', encoding = 'utf-8-sig') as file:
    lines = file.readlines()
    
oc_tt = list()
for line in lines:
    oc_tt.append(line.strip())
    
oriCode_tt = pd.DataFrame(data=oc_tt, columns=['OriginalCode'])

In [3]:
oriCode_tt.head()

                                        OriginalCode
0  private static Set < String > METHOD_1 ( TYPE_...
1  public TYPE_8 ( TYPE_1 VAR_2 , TYPE_2 VAR_3 ) ...
2  private void METHOD_1 ( ) { if ( ! VAR_1 . MET...
3  public void METHOD_1 ( ) throws TYPE_1 { Map <...
4  private TYPE_1 METHOD_1 ( List < TYPE_1 > VAR_...

In [4]:
with open('Dataset/test/tgt-test.txt', 'r', encoding = 'utf-8-sig') as file:
    lines = file.readlines()
    
rc_tt = list()
for line in lines:
    rc_tt.append(line.strip())
    
revCode_tt = pd.DataFrame(data=rc_tt, columns=['ReviewedCode'])

In [5]:
revCode_tt.head()

                                        ReviewedCode
0  private static Set < String > METHOD_1 ( TYPE_...
1  public TYPE_8 ( TYPE_1 VAR_2 , TYPE_2 VAR_3 ) ...
2  private void METHOD_1 ( ) { if ( ! VAR_1 . MET...
3  public void METHOD_1 ( ) throws TYPE_1 { final...
4  private TYPE_1 METHOD_1 ( List < TYPE_1 > VAR_...

In [6]:
data_tt = pd.DataFrame(pd.concat([oriCode_tt, revCode_tt], axis=1))

In [7]:
data_tt.head()

,OriginalCode,ReviewedCode
0,private static Set < String > METHOD_1 ( TYPE_...,private static Set < String > METHOD_1 ( TYPE_...
1,"public TYPE_8 ( TYPE_1 VAR_2 , TYPE_2 VAR_3 ) ...","public TYPE_8 ( TYPE_1 VAR_2 , TYPE_2 VAR_3 ) ..."
2,private void METHOD_1 ( ) { if ( ! VAR_1 . MET...,private void METHOD_1 ( ) { if ( ! VAR_1 . MET...
3,public void METHOD_1 ( ) throws TYPE_1 { Map <...,public void METHOD_1 ( ) throws TYPE_1 { final...
4,private TYPE_1 METHOD_1 ( List < TYPE_1 > VAR_...,private TYPE_1 METHOD_1 ( List < TYPE_1 > VAR_...

In [ ]:
data_tt.to_csv('bi_testingData.csv', index=False)

In [29]:
dtest = data_tt.to_dict(orient="records")

with open("test.jsonl", "w") as f:
    for line in dtest:
        f.write(json.dumps(line) + "\n")